### ISSUE TITLE
Not loading IPAC table

### ISSUE THREAD

**Issue by mjgraham** [atpy/atpy#28] opened 2011-09-01 05:34 UTC
The latest git version of ATpy is not loading this IPAC table properly: http://nsted.ipac.caltech.edu/data/ETSS/corot_exo/lightcurve/LRc02/EN2_STAR_CHR_0105891283_20080415T231048_20080907T224903_lc.tbl (saved to local disk as ipac_test.tbl)

```
>>> import atpy
>>> t = atpy.Table('ipac_test.tbl')
Auto-detected table type: ipac
WARNING: null value for column DATEJD changed from null to nan
WARNING: null value for column DATEHEL changed from null to nan
WARNING: null value for column REDFLUX changed from null to nan
WARNING: null value for column REDFLUXDEV changed from null to nan
WARNING: null value for column GREENFLUX changed from null to nan
WARNING: null value for column GREENFLUXDEV changed from null to nan
WARNING: null value for column BLUEFLUX changed from null to nan
WARNING: null value for column BLUEFLUXDEV changed from null to nan
WARNING: null value for column WHITEFLUX changed from null to nan
WARNING: null value for column STATUS changed from null to -9223372036854775807
WARNING: null value for column JCFW changed from null to nan
WARNING: null value for column BG changed from null to nan
WARNING: null value for column CORREC_RED changed from null to nan
WARNING: null value for column CORREC_GREEN changed from null to nan
WARNING: null value for column CORREC_BLUE changed from null to nan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/basetable.py", line 167, in __init__
    self.read(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/basetable.py", line 213, in read
    atpy._readers[table_type](self, *args, **kwargs)
  File "<string>", line 2, in read
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/decorators.py", line 36, in _auto_download_to_file
    return read(table, filename, *args, **kwargs)
  File "<string>", line 2, in read
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/decorators.py", line 55, in _auto_decompress_to_fileobj
    return read(table, filename, *args, **kwargs)
  File "<string>", line 2, in read
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/decorators.py", line 76, in _auto_fileobj_to_file
    return read(table, filename, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/6.0.0/lib/python2.6/site-packages/atpy/ipactable.py", line 273, in read
    array[name] = np.array(array[name], dtype=dtype)
ValueError: setting an array element with a sequence.
```

**Comment by taldcroft** [comment] 2011-09-01 12:00
You can read the referenced IPAC table directly with asciitable, or via the 'ascii' type in ATpy (which calls asciitable):

import asciitable
import atpy
dat = asciitable.read('ipac_test.tbl', Reader=asciitable.Ipac)
dat = atpy.Table('ipac_test.tbl', type='ascii', Reader=asciitable.Ipac)

**Comment by astrofrog** [comment] 2011-09-05 18:13
I can't reproduce this issue with a clean install of the latest version of ATpy. Can you confirm the checksum of the file?

```
$ md5 test_ipac.tbl 
MD5 (test_ipac.tbl) = 12def177cdc1e8a48f71d8dc7b20ff9e
```

**Comment by astrofrog** [comment] 2012-09-02 19:24
Since I can't reproduce this issue, I am closing this ticket. Feel free to re-open if you are still having issues.

**Closed as completed by astrofrog** 2012-09-02 19:24 UTC
