### ISSUE TITLE
data gets screwed up in writing fits tables

### ISSUE THREAD

**Issue by hamogu** [atpy/atpy#29] opened 2011-09-02 00:12 UTC
I discovered a severe problem in atpy. However, I am not entirely sure, if it is caused by atpy itself or by pyfits.
Here is an example:

```
import atpy
import numpy as np
a = [1.,2.,nan,nan]
a1 = np.array(a, dtype = '<f8')
a2 = np.array(a, dtype = '>f8')
>>> a1.dtype
dtype('float64')
>>> a2.dtype
dtype('>f8')
>>> test = atpy.Table()
>>> test.add_column('a1', a1)
>>> test.add_column('a2', a2)
>>> test.data
array([(1.0, 1.0), (2.0, 2.0), (nan, nan), (nan, nan)], 
    dtype=[('a1', '<f8'), ('a2', '>f8')])
>>> test.write('test.fits', overwrite = True)
Auto-detected table type: fits
>>> testr = atpy.Table('test.fits')
Auto-detected table type: fits
>>> testr.data
array([(1.0, 3.0386519416174186e-319), (2.0, 3.1620201333839779e-322),
    (nan, 3.1429986060190899e-319), (nan, 3.1429986060190899e-319)], 
    dtype=[('a1', '>f8'), ('a2', '>f8')])
```

When I look into the fits file, both columns have `TFORM1  = 'D       '` and I suspect that the error happens somewhere where the data is not properly transformed from big-endian to small-endian.
This worked with the old version of  `pyfits`, but not with 2.2.2 or 3.0.

**Comment by hamogu** [comment] 2011-09-02 12:03
This might indeed be a `pyfits` issue. I am just not sure if it is a bug or an undocumented feature, which allows you to prepare fits tables in a different endianness than you host machine. I will report this to STScI. I leave this issue open, because I suggest to implement at least a warning message in `atpy` as long `pyfits` quietly writes columns in different enidianess in single file. 
However, if you decide that this is not an atpy issue, that's also OK, I think the decision for this is with the `atpy` developers.

**Comment by astrofrog** [comment] 2011-09-05 18:57
I can confirm this is a Python bug with big-endian arrays:

```
Python 2.7.2 (default, Jun 27 2011, 10:02:22) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfits
>>> import numpy as np
>>> hdu = pyfits.BinTableHDU()
>>> c = pyfits.Column(name='a', array=np.array([1.,2.,3.], dtype = '>f8'), format='D')
>>> tab = pyfits.new_table([c])
>>> tab.writeto('test.fits', clobber=True)
Overwriting existing file 'test.fits'.
>>> pyfits.getdata('test.fits', 1)
FITS_rec([(3.0386519416174186e-319), (3.1620201333839779e-322),
       (1.0434666440167127e-320)], 
      dtype=[('a', '>f8')])
>>> 
```

I'll send this snippet to the PyFITS developers.

**Comment by astrofrog** [comment] 2011-09-06 15:09
For the record, this has been confirmed as a PyFITS bug: https://trac6.assembla.com/pyfits/ticket/77

**Comment by astrofrog** [comment] 2011-09-06 15:44
It looks like this is now fixed and should be in PyFITS 3.0.1: https://trac6.assembla.com/pyfits/changeset/1077

**Closed as completed by astrofrog** 2011-09-06 15:44 UTC

**Comment by cdeil** [comment] 2011-09-19 17:29
Aargh, I had the same problem, but because it was mixed with a second problem in my CSV data (non-ascii characters), it took me over an hour to figure out that there is actually a pyfits bug.

For the future, could you make atpy install the unittests and make them easily runnable?

``` python
>>> atpy.test()
```

That might have helped me here (pyfits also seems to have a ton of tests, but I don't see how to easily run them all.

Thanks!

**Comment by astrofrog** [comment] 2011-10-16 23:25
@cdeil - good idea, I've opened a feature request ticket to keep track of this: https://github.com/atpy/atpy/issues/32
